name: Code Analysis

on:
  push:
  pull_request:

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint-action
        with:
          tool-name: pycodestyle
          tool-package: pytest-pycodestyle
          pytest-args: --pycodestyle --ignore=E721,E121,E123,E126,E133,E226,E241,E242,E704,W503,W504 --max-line-length=125

  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint-action
        with:
          tool-name: pyflakes
          tool-package: pytest-flakes
          pytest-args: --flakes

  pydocstyle:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint-action
        with:
          tool-name: pydocstyle
          tool-package: pytest-docstyle
          pytest-args: --docstyle --docstyle-select=D101,D102,D103,D105,D106,D207,D208,D209,D210,D211,D213,D214,D215,D300,D414,D417,D418,D419
          continue-on-error: 'true'

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/shellcheck-action
        with:
          shellcheck-args: -e SC1091

  publish-test-results:
    runs-on: ubuntu-latest
    needs: [pycodestyle, pyflakes, pydocstyle, shellcheck]
    if: always()
    steps:
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: test-results
          
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Code Analysis Tests
          path: 'test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false
