name: Code Analysis

on:
  push:
  pull_request:

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint-action
        with:
          tool-name: pycodestyle
          tool-package: pytest-pycodestyle
          pytest-args: --pycodestyle --ignore=E721,E121,E123,E126,E133,E226,E241,E242,E704,W503,W504 --max-line-length=125

  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint-action
        with:
          tool-name: pyflakes
          tool-package: pytest-flakes
          pytest-args: --flakes

  pydocstyle:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-lint-action
        with:
          tool-name: pydocstyle
          tool-package: pytest-docstyle
          pytest-args: --docstyle --docstyle-select=D101,D102,D103,D105,D106,D207,D208,D209,D210,D211,D213,D214,D215,D300,D414,D417,D418,D419
          continue-on-error: 'true'

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/shellcheck-action
        with:
          shellcheck-args: -e SC1091

  publish-test-results:
    runs-on: ubuntu-latest
    needs: [pycodestyle, pyflakes, pydocstyle, shellcheck]
    if: always()
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: test-results
          
      - name: Debug git repository
        run: |
          pwd
          ls -la
          echo "Git workspace: ${{ github.workspace }}"
          echo "Current directory: $(pwd)"
          git status || echo "Git status failed"
          git log --oneline -1 || echo "Git log failed"
          ls -la .git || echo "No .git directory found"
          
      - name: Publish test results
        uses: dorny/test-reporter@v1.9.1
        if: always()
        continue-on-error: true
        with:
          name: Code Analysis Tests
          path: test-results/**/*.xml
          reporter: java-junit
          fail-on-error: false
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-empty: true
          only-summary: false
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ github.workspace }}
          
      - name: Alternative test results publication
        if: failure()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'test-results/**/*.xml'
          check_name: 'Code Analysis Tests (Alternative)'
          fail_on_failure: false
          require_tests: false
